package com.quare.nuplist.core.theme.color.palette

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val primaryLight = Color(0xFF8A4A64)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD9E4)
val onPrimaryContainerLight = Color(0xFF6F334C)
val secondaryLight = Color(0xFF735760)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD9E4)
val onSecondaryContainerLight = Color(0xFF5A3F49)
val tertiaryLight = Color(0xFF7D5637)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDCC4)
val onTertiaryContainerLight = Color(0xFF633E22)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F8)
val onBackgroundLight = Color(0xFF21191C)
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF21191C)
val surfaceVariantLight = Color(0xFFF2DDE2)
val onSurfaceVariantLight = Color(0xFF514347)
val outlineLight = Color(0xFF837377)
val outlineVariantLight = Color(0xFFD5C2C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372E31)
val inverseOnSurfaceLight = Color(0xFFFDEDF0)
val inversePrimaryLight = Color(0xFFFFB0CD)
val surfaceDimLight = Color(0xFFE6D6DA)
val surfaceBrightLight = Color(0xFFFFF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F3)
val surfaceContainerLight = Color(0xFFFAEAED)
val surfaceContainerHighLight = Color(0xFFF4E4E8)
val surfaceContainerHighestLight = Color(0xFFEEDFE2)
